# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Attire
email: david.sosa.valdes@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An implementation of Twig template engine combined with Assetic asset management framework for CodeIgniter 3.0.
baseurl: "/Attire" # the subpath of your site, e.g. /blog
url: "https://github.com/davidsosavaldes" # the base hostname & protocol for your site
github_username: davidsosavaldes

# Build settings
markdown: kramdown

sass:
    style: :compressed