# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 'Attire'
email: david.sosa.valdes@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/Attire" # the subpath of your site, e.g. /blog
url: "http://davidsosavaldes.github.io" # the base hostname & protocol for your site
github_username: davidsosavaldes

# Build settings
markdown: kramdown

# jekyll-tagging
tag_page_layout: tag_page
tag_page_dir: tag
