site_name: Attire
site_url: https://gitlab.com/david-sosa-valdes/ci-twig
site_description: CI-Twig it's a simple implementation of Twig template engine for CodeIgniter. It supports themes, layouts, templates for regular apps and also for apps that use HMVC.
site_author: David Sosa Valdes

repo_url: https://github.com/mkdocs/mkdocs/

pages:
- ['index.md','Home']
- ['user-guide/writing-themes.md','User Guide','Creating your themes']
- ['user-guide/extending-environment.md','User Guide','Extending Twig Environment']
- ['about/release-notes.md','About','Release notes']
- ['about/contributing.md','About','Contributing']
- ['about/license.md','About','Licence']

theme: readthedocs

google_analytics: ['UA-41717346-3', 'ci-attire.readthedocs.org/en/latest/']

copyright: Copyright &copy; 2015 <a href="https://gitlab.com/david-sosa-valdes">David Sosa Valdes</a>.<br><div>Icons made by <a href="http://www.flaticon.com/authors/tutsplus" title="TutsPlus">TutsPlus</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0">CC BY 3.0</a> / Desaturated from original.</div>